version: '2'
services:
    web:
        image: nginx:latest
        ports:
            - "3334:80"
        volumes:
            - ./code:/code
            - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
    php:
        image: php:7-fpm
        ports:
            - 9001:9001
        volumes:
            - ./code:/code
  